# Generated by Django 3.1 on 2020-08-21 07:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.nodetype')),
            ],
            options={
                'db_table': 'cake_node_type',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField()),
                ('source_url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('public', 'public'), ('draft', 'draft')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('node_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='node.nodetype')),
            ],
            options={
                'db_table': 'cake_node',
            },
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['node_type'], name='cake_node_node_ty_b3272e_idx'),
        ),
    ]
